# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'dotenv-rails', groups: %i[development test]
gem 'rspec', '~> 3.11'
gem 'twilio-ruby', '~> 5.73.0'
